apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: openteletemtry-example-users-api:20220923-002
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: users-api-svc
        resources: 
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OPENTELEMETRY_COLLECTOR_URL
          value: "$(NODE_IP):4317"
        - name: OPENTELEMETRY_SERVICE_NAME
          value: "users-api-service"
        - name: OPENTELEMETRY_DEPLOYMENT_ENVIRONMENT
          value: "development"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
      - name: orders-api
        image: openteletemtry-example-orders-api:20220923-002
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: orders-api-svc
        resources: 
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OPENTELEMETRY_COLLECTOR_URL
          value: "$(NODE_IP):4317"
        - name: OPENTELEMETRY_SERVICE_NAME
          value: "orders-api-service"
        - name: OPENTELEMETRY_DEPLOYMENT_ENVIRONMENT
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-service
spec:
  # type: NodePort
  selector:
    app: users-api
  ports:
  - name: users-api-port
    protocol: TCP
    port: 80
    targetPort: users-api-svc
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api-service
spec:
  type: NodePort
  selector:
    app: orders-api
  ports:
  - name: orders-api-port
    protocol: TCP
    port: 80
    targetPort: orders-api-svc
    nodePort: 30303